sonar.projectKey=eliet9999_requests
sonar.organization=eliet9999

sonar.sources=src/requests
sonar.tests=tests

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=true
